var classes = [
    {
        "name": "Planck\\ApplicationInstaller",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "install",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "initializeContainers",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getDatabasePath",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "initializeDatabase",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "executeSQLInPath",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "loadDatabase",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "executeSQL",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "initializeLangPath",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 9,
        "nbMethods": 9,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 9,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 14,
        "ccn": 6,
        "ccnMethodMax": 3,
        "externals": [
            "Planck\\Exception",
            "Phi\\Database\\Driver\\PDO\\Source",
            "Phi\\Database\\Source",
            "Phi\\Database\\Driver\\PDO\\Source",
            "Phi\\Database\\Source"
        ],
        "parents": [],
        "lcom": 1,
        "length": 204,
        "vocabulary": 61,
        "volume": 1209.87,
        "difficulty": 5.12,
        "effort": 6197.93,
        "level": 0.2,
        "bugs": 0.4,
        "time": 344,
        "intelligentContent": 236.17,
        "number_operators": 58,
        "number_operands": 146,
        "number_operators_unique": 4,
        "number_operands_unique": 57,
        "cloc": 0,
        "loc": 86,
        "lloc": 86,
        "mi": 35.41,
        "mIwoC": 35.41,
        "commentWeight": 0,
        "kanDefect": 0.66,
        "relativeStructuralComplexity": 81,
        "relativeDataComplexity": 0.46,
        "relativeSystemComplexity": 81.46,
        "totalStructuralComplexity": 729,
        "totalDataComplexity": 4.1,
        "totalSystemComplexity": 733.1,
        "package": "Planck\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Planck\\Bootstrap",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "check",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [],
        "parents": [],
        "lcom": 1,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 0,
        "loc": 8,
        "lloc": 8,
        "mi": 171,
        "mIwoC": 171,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 1,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 1,
        "package": "Planck\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "Planck\\Container",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "initialize",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Phi\\Container\\Container"
        ],
        "parents": [
            "Phi\\Container\\Container"
        ],
        "lcom": 1,
        "length": 1,
        "vocabulary": 1,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 2,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 1,
        "number_operators_unique": 0,
        "number_operands_unique": 1,
        "cloc": 0,
        "loc": 11,
        "lloc": 11,
        "mi": 171,
        "mIwoC": 171,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 1,
        "totalStructuralComplexity": 2,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 2,
        "package": "Planck\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Planck\\Controller",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "initialize",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Phi\\Application\\Controller",
            "Phi\\Application\\Application",
            "parent"
        ],
        "parents": [
            "Phi\\Application\\Controller"
        ],
        "lcom": 1,
        "length": 3,
        "vocabulary": 2,
        "volume": 3,
        "difficulty": 0,
        "effort": 0,
        "level": 1.33,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 4,
        "number_operators": 0,
        "number_operands": 3,
        "number_operators_unique": 0,
        "number_operands_unique": 2,
        "cloc": 0,
        "loc": 13,
        "lloc": 13,
        "mi": 72.23,
        "mIwoC": 72.23,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 0.17,
        "relativeSystemComplexity": 4.17,
        "totalStructuralComplexity": 8,
        "totalDataComplexity": 0.33,
        "totalSystemComplexity": 8.33,
        "package": "Planck\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Planck\\DataLayer",
        "interface": false,
        "abstract": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [],
        "parents": [],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 0,
        "loc": 5,
        "lloc": 5,
        "mi": 171,
        "mIwoC": 171,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "Planck\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "Planck\\Exception\\ClassDoesNotExist",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Planck\\Exception\\DoesNotExist",
            "parent"
        ],
        "parents": [
            "Planck\\Exception\\DoesNotExist"
        ],
        "lcom": 1,
        "length": 6,
        "vocabulary": 4,
        "volume": 12,
        "difficulty": 0.67,
        "effort": 8,
        "level": 1.5,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 18,
        "number_operators": 2,
        "number_operands": 4,
        "number_operators_unique": 1,
        "number_operands_unique": 3,
        "cloc": 0,
        "loc": 8,
        "lloc": 8,
        "mi": 72.61,
        "mIwoC": 72.61,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 1.5,
        "package": "Planck\\Exception\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Planck\\Exception\\DoesNotExist",
        "interface": false,
        "abstract": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [
            "Planck\\Exception"
        ],
        "parents": [
            "Planck\\Exception"
        ],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 0,
        "loc": 4,
        "lloc": 4,
        "mi": 171,
        "mIwoC": 171,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "Planck\\Exception\\",
        "pageRank": 0.05,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "Planck\\Exception\\InvalidValue",
        "interface": false,
        "abstract": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [
            "Planck\\Exception"
        ],
        "parents": [
            "Planck\\Exception"
        ],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 0,
        "loc": 4,
        "lloc": 4,
        "mi": 171,
        "mIwoC": 171,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "Planck\\Exception\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Planck\\Exception\\Unauthorized",
        "interface": false,
        "abstract": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [
            "Planck\\Exception"
        ],
        "parents": [
            "Planck\\Exception"
        ],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 0,
        "loc": 4,
        "lloc": 4,
        "mi": 171,
        "mIwoC": 171,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "Planck\\Exception\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Planck\\Exception",
        "interface": false,
        "abstract": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [
            "Phi\\Core\\Exception"
        ],
        "parents": [
            "Phi\\Core\\Exception"
        ],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 0,
        "loc": 4,
        "lloc": 4,
        "mi": 171,
        "mIwoC": 171,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "Planck\\",
        "pageRank": 0.34,
        "afferentCoupling": 5,
        "efferentCoupling": 1,
        "instability": 0.17,
        "violations": {}
    },
    {
        "name": "Planck\\Helper\\Date",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "formatDatetime",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [],
        "parents": [],
        "lcom": 1,
        "length": 6,
        "vocabulary": 4,
        "volume": 12,
        "difficulty": 0.83,
        "effort": 10,
        "level": 1.2,
        "bugs": 0,
        "time": 1,
        "intelligentContent": 14.4,
        "number_operators": 1,
        "number_operands": 5,
        "number_operators_unique": 1,
        "number_operands_unique": 3,
        "cloc": 0,
        "loc": 8,
        "lloc": 8,
        "mi": 72.61,
        "mIwoC": 72.61,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 3,
        "relativeSystemComplexity": 3,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 3,
        "totalSystemComplexity": 3,
        "package": "Planck\\Helper\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "Planck\\Helper\\File",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "getExtension",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "sanitizePath",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "normalize",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "recursiveRmdir",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "rcopy",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "doOnPathes",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "rglob",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 7,
        "nbMethods": 7,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 7,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 34,
        "ccn": 28,
        "ccnMethodMax": 14,
        "externals": [
            "static",
            "static",
            "static",
            "static"
        ],
        "parents": [],
        "lcom": 7,
        "length": 263,
        "vocabulary": 44,
        "volume": 1435.83,
        "difficulty": 21.6,
        "effort": 31013.94,
        "level": 0.05,
        "bugs": 0.48,
        "time": 1723,
        "intelligentContent": 66.47,
        "number_operators": 95,
        "number_operands": 168,
        "number_operators_unique": 9,
        "number_operands_unique": 35,
        "cloc": 4,
        "loc": 119,
        "lloc": 115,
        "mi": 43.19,
        "mIwoC": 29.18,
        "commentWeight": 14.01,
        "kanDefect": 2.49,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 4.07,
        "relativeSystemComplexity": 5.07,
        "totalStructuralComplexity": 7,
        "totalDataComplexity": 28.5,
        "totalSystemComplexity": 35.5,
        "package": "Planck\\Helper\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Planck\\Helper\\StringUtil",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "slugify",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "removeAccent",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "escapeRegexp",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "separatedToClassName",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "toCamelCase",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "camelCaseToSeparated",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getClassBaseName",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "mb_ucfirst",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 8,
        "nbMethods": 8,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 8,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 13,
        "ccn": 6,
        "ccnMethodMax": 3,
        "externals": [
            "static",
            "self",
            "static",
            "static"
        ],
        "parents": [],
        "lcom": 8,
        "length": 205,
        "vocabulary": 45,
        "volume": 1125.83,
        "difficulty": 9.38,
        "effort": 10554.66,
        "level": 0.11,
        "bugs": 0.38,
        "time": 586,
        "intelligentContent": 120.09,
        "number_operators": 55,
        "number_operands": 150,
        "number_operators_unique": 5,
        "number_operands_unique": 40,
        "cloc": 2,
        "loc": 81,
        "lloc": 79,
        "mi": 48.48,
        "mIwoC": 36.43,
        "commentWeight": 12.05,
        "kanDefect": 0.5,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 5.08,
        "relativeSystemComplexity": 9.08,
        "totalStructuralComplexity": 32,
        "totalDataComplexity": 40.67,
        "totalSystemComplexity": 72.67,
        "package": "Planck\\Helper\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Planck\\Session",
        "interface": false,
        "abstract": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [
            "Phi\\Session\\Session"
        ],
        "parents": [
            "Phi\\Session\\Session"
        ],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 0,
        "loc": 4,
        "lloc": 4,
        "mi": 171,
        "mIwoC": 171,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "Planck\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Planck\\State\\Dimension",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "__construct",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getName",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getDescriptor",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 2,
        "nbMethodsSetters": 1,
        "wmc": 3,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [],
        "parents": [],
        "lcom": 1,
        "length": 8,
        "vocabulary": 4,
        "volume": 16,
        "difficulty": 2.5,
        "effort": 40,
        "level": 0.4,
        "bugs": 0.01,
        "time": 2,
        "intelligentContent": 6.4,
        "number_operators": 3,
        "number_operands": 5,
        "number_operators_unique": 2,
        "number_operands_unique": 2,
        "cloc": 0,
        "loc": 18,
        "lloc": 18,
        "mi": 64.05,
        "mIwoC": 64.05,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 2.33,
        "relativeSystemComplexity": 2.33,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 7,
        "totalSystemComplexity": 7,
        "package": "Planck\\State\\",
        "pageRank": 0.15,
        "afferentCoupling": 2,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "Planck\\State\\DimensionValue",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setValue",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getValue",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getDimension",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 2,
        "nbMethodsSetters": 0,
        "wmc": 6,
        "ccn": 3,
        "ccnMethodMax": 3,
        "externals": [
            "Planck\\State\\Dimension"
        ],
        "parents": [],
        "lcom": 1,
        "length": 39,
        "vocabulary": 11,
        "volume": 134.92,
        "difficulty": 10.83,
        "effort": 1461.61,
        "level": 0.09,
        "bugs": 0.04,
        "time": 81,
        "intelligentContent": 12.45,
        "number_operators": 13,
        "number_operands": 26,
        "number_operators_unique": 5,
        "number_operands_unique": 6,
        "cloc": 6,
        "loc": 37,
        "lloc": 31,
        "mi": 81.36,
        "mIwoC": 52.15,
        "commentWeight": 29.21,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1.38,
        "relativeSystemComplexity": 2.38,
        "totalStructuralComplexity": 4,
        "totalDataComplexity": 5.5,
        "totalSystemComplexity": 9.5,
        "package": "Planck\\State\\",
        "pageRank": 0.04,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "Planck\\State",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "addDimension",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getDimensions",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getValue",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getValueObject",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "relayEvent",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getValues",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getDimension",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setValue",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 8,
        "nbMethods": 6,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 5,
        "nbMethodsGetter": 2,
        "nbMethodsSetters": 0,
        "wmc": 10,
        "ccn": 3,
        "ccnMethodMax": 2,
        "externals": [
            "Planck\\State\\Dimension",
            "Planck\\State\\DimensionValue",
            "Phi\\Event\\Event",
            "Planck\\Exception"
        ],
        "parents": [],
        "lcom": 2,
        "length": 86,
        "vocabulary": 16,
        "volume": 344,
        "difficulty": 10.5,
        "effort": 3612,
        "level": 0.1,
        "bugs": 0.11,
        "time": 201,
        "intelligentContent": 32.76,
        "number_operators": 23,
        "number_operands": 63,
        "number_operators_unique": 4,
        "number_operands_unique": 12,
        "cloc": 6,
        "loc": 66,
        "lloc": 60,
        "mi": 65.56,
        "mIwoC": 43.05,
        "commentWeight": 22.51,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 81,
        "relativeDataComplexity": 0.99,
        "relativeSystemComplexity": 81.99,
        "totalStructuralComplexity": 648,
        "totalDataComplexity": 7.9,
        "totalSystemComplexity": 655.9,
        "package": "Planck\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Planck\\Tool\\Encrypt",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "encrypt",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "decrypt",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [],
        "parents": [],
        "lcom": 1,
        "length": 61,
        "vocabulary": 14,
        "volume": 232.25,
        "difficulty": 3.92,
        "effort": 909.64,
        "level": 0.26,
        "bugs": 0.08,
        "time": 51,
        "intelligentContent": 59.3,
        "number_operators": 14,
        "number_operands": 47,
        "number_operators_unique": 2,
        "number_operands_unique": 12,
        "cloc": 0,
        "loc": 30,
        "lloc": 30,
        "mi": 51.08,
        "mIwoC": 51.08,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 3.33,
        "relativeSystemComplexity": 3.33,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 10,
        "totalSystemComplexity": 10,
        "package": "Planck\\Tool\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "Planck\\Traits\\Decorable",
        "interface": false,
        "abstract": true,
        "methods": [
            {
                "name": "decorate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isDecorated",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 4,
        "ccn": 3,
        "ccnMethodMax": 2,
        "externals": [
            "Planck\\Model\\Exception\\ClassDoesNotExist",
            "decoratorClassName"
        ],
        "parents": [],
        "lcom": 2,
        "length": 16,
        "vocabulary": 6,
        "volume": 41.36,
        "difficulty": 5,
        "effort": 206.8,
        "level": 0.2,
        "bugs": 0.01,
        "time": 11,
        "intelligentContent": 8.27,
        "number_operators": 6,
        "number_operands": 10,
        "number_operators_unique": 3,
        "number_operands_unique": 3,
        "cloc": 4,
        "loc": 23,
        "lloc": 19,
        "mi": 90.48,
        "mIwoC": 60.38,
        "commentWeight": 30.1,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 4,
        "relativeSystemComplexity": 4,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 8,
        "totalSystemComplexity": 8,
        "package": "Planck\\Traits\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Planck\\Traits\\HasLocalResource",
        "interface": false,
        "abstract": true,
        "methods": [
            {
                "name": "addFrontPackage",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getFrontPackages",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 1,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Planck\\View\\Package"
        ],
        "parents": [],
        "lcom": 1,
        "length": 12,
        "vocabulary": 5,
        "volume": 27.86,
        "difficulty": 2.67,
        "effort": 74.3,
        "level": 0.38,
        "bugs": 0.01,
        "time": 4,
        "intelligentContent": 10.45,
        "number_operators": 4,
        "number_operands": 8,
        "number_operators_unique": 2,
        "number_operands_unique": 3,
        "cloc": 68,
        "loc": 83,
        "lloc": 15,
        "mi": 113.38,
        "mIwoC": 64.09,
        "commentWeight": 49.29,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 2.5,
        "relativeSystemComplexity": 2.5,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 5,
        "totalSystemComplexity": 5,
        "package": "Planck\\Traits\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Planck\\Traits\\IsApplicationObject",
        "interface": false,
        "abstract": true,
        "methods": [
            {
                "name": "getDefaultApplication",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "_initializeTraitIsApplicationObject",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setApplication",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getApplication",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getFromContainer",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 5,
        "nbMethods": 5,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 5,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 6,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "Planck\\Application\\ApplicationRegistry",
            "Planck\\Application\\Application",
            "Planck\\Application\\Application",
            "self"
        ],
        "parents": [],
        "lcom": 2,
        "length": 21,
        "vocabulary": 6,
        "volume": 54.28,
        "difficulty": 6,
        "effort": 325.71,
        "level": 0.17,
        "bugs": 0.02,
        "time": 18,
        "intelligentContent": 9.05,
        "number_operators": 9,
        "number_operands": 12,
        "number_operators_unique": 3,
        "number_operands_unique": 3,
        "cloc": 10,
        "loc": 40,
        "lloc": 30,
        "mi": 90.33,
        "mIwoC": 55.36,
        "commentWeight": 34.97,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 25,
        "relativeDataComplexity": 0.9,
        "relativeSystemComplexity": 25.9,
        "totalStructuralComplexity": 125,
        "totalDataComplexity": 4.5,
        "totalSystemComplexity": 129.5,
        "package": "Planck\\Traits\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "Planck\\Traits\\IsExtensionObject",
        "interface": false,
        "abstract": true,
        "methods": [
            {
                "name": "getModuleName",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getExtensionName",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "buildURL",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getExtension",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getModule",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 5,
        "nbMethods": 5,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 5,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 9,
        "ccn": 5,
        "ccnMethodMax": 2,
        "externals": [],
        "parents": [],
        "lcom": 1,
        "length": 52,
        "vocabulary": 12,
        "volume": 186.42,
        "difficulty": 6,
        "effort": 1118.51,
        "level": 0.17,
        "bugs": 0.06,
        "time": 62,
        "intelligentContent": 31.07,
        "number_operators": 16,
        "number_operands": 36,
        "number_operators_unique": 3,
        "number_operands_unique": 9,
        "cloc": 0,
        "loc": 44,
        "lloc": 44,
        "mi": 47.58,
        "mIwoC": 47.58,
        "commentWeight": 0,
        "kanDefect": 0.43,
        "relativeStructuralComplexity": 36,
        "relativeDataComplexity": 0.8,
        "relativeSystemComplexity": 36.8,
        "totalStructuralComplexity": 180,
        "totalDataComplexity": 4,
        "totalSystemComplexity": 184,
        "package": "Planck\\Traits\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "Planck\\Traits\\Listenable",
        "interface": false,
        "abstract": true,
        "methods": [
            {
                "name": "loadListeners",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 6,
        "ccn": 6,
        "ccnMethodMax": 6,
        "externals": [
            "Planck\\Application\\Application"
        ],
        "parents": [],
        "lcom": 1,
        "length": 40,
        "vocabulary": 10,
        "volume": 132.88,
        "difficulty": 6.64,
        "effort": 882.68,
        "level": 0.15,
        "bugs": 0.04,
        "time": 49,
        "intelligentContent": 20,
        "number_operators": 9,
        "number_operands": 31,
        "number_operators_unique": 3,
        "number_operands_unique": 7,
        "cloc": 3,
        "loc": 31,
        "lloc": 28,
        "mi": 75.93,
        "mIwoC": 52.76,
        "commentWeight": 23.17,
        "kanDefect": 0.98,
        "relativeStructuralComplexity": 25,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 25,
        "totalStructuralComplexity": 25,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 25,
        "package": "Planck\\Traits\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    }
]